pub struct Words {
    pub goal: &'static str,
    pub level: &'static str,
    pub estimate: &'static str,
    pub hour: &'static str,
    pub stages: &'static str,
    pub children: &'static str,
    pub pending: &'static str,
    pub sources: &'static str,
    pub checked: &'static str,
    pub diagram: &'static str,
    pub license: &'static str,
    pub author: &'static str,
    pub source: &'static str,
    pub practice: &'static str,
    pub deliverable: &'static str,
    pub constraints: &'static str,
    pub acceptance: &'static str,
    pub check: &'static str,
    pub expect: &'static str,
    pub questions: &'static str,
    pub hidden: &'static str,
}

const RU: Words = Words {
    goal: "Цель",
    level: "Уровень",
    estimate: "Объём по карте",
    hour: "ч",
    stages: "Этапы",
    children: "Подпрограммы",
    pending: "ждёт генерации",
    sources: "Источники",
    checked: "проверено",
    diagram: "Схема",
    license: "Лицензия",
    author: "Автор",
    source: "Источник",
    practice: "Практика",
    deliverable: "Результат",
    constraints: "Ограничения",
    acceptance: "Приёмка",
    check: "проверка",
    expect: "ожидание",
    questions: "Вопросы",
    hidden: "Эталонные ответы не экспортированы: этап не зачтён.",
};

const EN: Words = Words {
    goal: "Goal",
    level: "Level",
    estimate: "Map estimate",
    hour: "h",
    stages: "Stages",
    children: "Subprograms",
    pending: "not generated yet",
    sources: "Sources",
    checked: "checked",
    diagram: "Diagram",
    license: "License",
    author: "Author",
    source: "Source",
    practice: "Practice",
    deliverable: "Deliverable",
    constraints: "Constraints",
    acceptance: "Acceptance",
    check: "check",
    expect: "expected",
    questions: "Questions",
    hidden: "Reference answers are not exported: the stage is not passed yet.",
};

pub fn of(locale: &str) -> &'static Words {
    if locale.starts_with("ru") { &RU } else { &EN }
}
