[package]
name = "tolearn-runner"
description = "Execution of practice check commands"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
tolearn-core.workspace = true

[lints]
workspace = true
